#if defined(__linux__) && defined(ENGINE_HAS_WAYLAND)

#include <engine/core/platform_window.hpp>
#include <engine/core/log.hpp>

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <xkbcommon/xkbcommon.h>
#include <poll.h>
#include <unistd.h>
#include <cstring>
#include <cstdlib>
#include <sys/mman.h>

// Generated by wayland-scanner from protocol XML — see CMakeLists.txt
#include "xdg-shell-client-protocol.h"
#include "xdg-decoration-unstable-v1-client-protocol.h"

namespace engine::core {

class WaylandWindow : public PlatformWindow {
public:
    ~WaylandWindow() override { destroy(); }

    bool probe_display() {
        wl_display* d = wl_display_connect(nullptr);
        if (!d) return false;
        wl_display_disconnect(d);
        return true;
    }

    bool create(const WindowSettings& ws, const WindowCallbacks& callbacks) override {
        m_callbacks = callbacks;

        m_display = wl_display_connect(nullptr);
        if (!m_display) {
            log(LogLevel::Error, "Failed to connect to Wayland display");
            return false;
        }

        m_xkb_ctx = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
        if (!m_xkb_ctx) {
            log(LogLevel::Error, "Failed to create XKB context");
            destroy();
            return false;
        }

        m_registry = wl_display_get_registry(m_display);
        wl_registry_add_listener(m_registry, &s_registry_listener, this);
        wl_display_roundtrip(m_display);

        if (!m_compositor) {
            log(LogLevel::Error, "Wayland compositor not found");
            destroy();
            return false;
        }
        if (!m_xdg_wm_base) {
            log(LogLevel::Error, "xdg_wm_base not found — compositor lacks xdg-shell support");
            destroy();
            return false;
        }

        m_surface = wl_compositor_create_surface(m_compositor);
        if (!m_surface) {
            log(LogLevel::Error, "Failed to create Wayland surface");
            destroy();
            return false;
        }

        m_xdg_surface = xdg_wm_base_get_xdg_surface(m_xdg_wm_base, m_surface);
        xdg_surface_add_listener(m_xdg_surface, &s_xdg_surface_listener, this);

        m_toplevel = xdg_surface_get_toplevel(m_xdg_surface);
        xdg_toplevel_add_listener(m_toplevel, &s_toplevel_listener, this);
        xdg_toplevel_set_title(m_toplevel, ws.title.c_str());
        xdg_toplevel_set_app_id(m_toplevel, "engine");

        // Request server-side decorations if available
        if (m_deco_manager) {
            m_decoration = zxdg_decoration_manager_v1_get_toplevel_decoration(
                m_deco_manager, m_toplevel);
            zxdg_toplevel_decoration_v1_set_mode(
                m_decoration, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
        }

        if (ws.fullscreen) {
            xdg_toplevel_set_fullscreen(m_toplevel, nullptr);
        }

        wl_surface_commit(m_surface);

        // Wait for the initial configure event
        m_width = ws.width;
        m_height = ws.height;
        while (!m_configured) {
            wl_display_dispatch(m_display);
        }

        return true;
    }

    void destroy() override {
        if (m_decoration) { zxdg_toplevel_decoration_v1_destroy(m_decoration); m_decoration = nullptr; }
        if (m_toplevel) { xdg_toplevel_destroy(m_toplevel); m_toplevel = nullptr; }
        if (m_xdg_surface) { xdg_surface_destroy(m_xdg_surface); m_xdg_surface = nullptr; }
        if (m_surface) { wl_surface_destroy(m_surface); m_surface = nullptr; }
        if (m_pointer) { wl_pointer_destroy(m_pointer); m_pointer = nullptr; }
        if (m_keyboard) { wl_keyboard_destroy(m_keyboard); m_keyboard = nullptr; }
        if (m_deco_manager) { zxdg_decoration_manager_v1_destroy(m_deco_manager); m_deco_manager = nullptr; }
        if (m_xdg_wm_base) { xdg_wm_base_destroy(m_xdg_wm_base); m_xdg_wm_base = nullptr; }
        if (m_seat) { wl_seat_destroy(m_seat); m_seat = nullptr; }
        if (m_compositor) { wl_compositor_destroy(m_compositor); m_compositor = nullptr; }
        if (m_registry) { wl_registry_destroy(m_registry); m_registry = nullptr; }
        if (m_xkb_state) { xkb_state_unref(m_xkb_state); m_xkb_state = nullptr; }
        if (m_xkb_keymap) { xkb_keymap_unref(m_xkb_keymap); m_xkb_keymap = nullptr; }
        if (m_xkb_ctx) { xkb_context_unref(m_xkb_ctx); m_xkb_ctx = nullptr; }
        if (m_display) { wl_display_disconnect(m_display); m_display = nullptr; }
        m_configured = false;
    }

    bool poll_events() override {
        if (!m_display) return false;

        // Non-blocking event dispatch
        while (wl_display_prepare_read(m_display) != 0) {
            wl_display_dispatch_pending(m_display);
        }

        if (wl_display_flush(m_display) < 0) {
            wl_display_cancel_read(m_display);
            m_closed = true;
            return false;
        }

        struct pollfd pfd = {};
        pfd.fd = wl_display_get_fd(m_display);
        pfd.events = POLLIN;

        if (poll(&pfd, 1, 0) > 0) {
            wl_display_read_events(m_display);
            wl_display_dispatch_pending(m_display);
        } else {
            wl_display_cancel_read(m_display);
        }

        return !m_closed;
    }

    NativeHandles native_handles() const override {
        NativeHandles h;
        h.display = m_display;
        h.window  = m_surface;
        h.backend = WindowBackend::Wayland;
        return h;
    }

    uint32_t width() const override { return m_width; }
    uint32_t height() const override { return m_height; }

    void set_fullscreen(bool fs) override {
        if (!m_toplevel) return;
        if (fs)
            xdg_toplevel_set_fullscreen(m_toplevel, nullptr);
        else
            xdg_toplevel_unset_fullscreen(m_toplevel);
        wl_surface_commit(m_surface);
        wl_display_flush(m_display);
    }

private:
    // ── Registry listener ──────────────────────────────────────────────
    static void registry_global(void* data, wl_registry* reg, uint32_t name,
                                const char* interface, uint32_t version) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (std::strcmp(interface, wl_compositor_interface.name) == 0) {
            self->m_compositor = static_cast<wl_compositor*>(
                wl_registry_bind(reg, name, &wl_compositor_interface, 4));
        } else if (std::strcmp(interface, xdg_wm_base_interface.name) == 0) {
            self->m_xdg_wm_base = static_cast<xdg_wm_base*>(
                wl_registry_bind(reg, name, &xdg_wm_base_interface, 1));
            xdg_wm_base_add_listener(self->m_xdg_wm_base, &s_wm_base_listener, self);
        } else if (std::strcmp(interface, wl_seat_interface.name) == 0) {
            self->m_seat = static_cast<wl_seat*>(
                wl_registry_bind(reg, name, &wl_seat_interface, 5));
            wl_seat_add_listener(self->m_seat, &s_seat_listener, self);
        } else if (std::strcmp(interface, zxdg_decoration_manager_v1_interface.name) == 0) {
            self->m_deco_manager = static_cast<zxdg_decoration_manager_v1*>(
                wl_registry_bind(reg, name, &zxdg_decoration_manager_v1_interface, 1));
        }
        (void)version;
    }
    static void registry_global_remove(void*, wl_registry*, uint32_t) {}

    static constexpr wl_registry_listener s_registry_listener = {
        registry_global, registry_global_remove
    };

    // ── xdg_wm_base listener (ping/pong) ──────────────────────────────
    static void wm_base_ping(void*, xdg_wm_base* base, uint32_t serial) {
        xdg_wm_base_pong(base, serial);
    }
    static constexpr xdg_wm_base_listener s_wm_base_listener = { wm_base_ping };

    // ── xdg_surface listener ──────────────────────────────────────────
    static void xdg_surface_configure(void* data, xdg_surface* surface, uint32_t serial) {
        auto* self = static_cast<WaylandWindow*>(data);
        xdg_surface_ack_configure(surface, serial);
        self->m_configured = true;
    }
    static constexpr xdg_surface_listener s_xdg_surface_listener = { xdg_surface_configure };

    // ── xdg_toplevel listener ─────────────────────────────────────────
    static void toplevel_configure(void* data, xdg_toplevel*, int32_t w, int32_t h, wl_array*) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (w > 0 && h > 0) {
            uint32_t new_w = static_cast<uint32_t>(w);
            uint32_t new_h = static_cast<uint32_t>(h);
            if (new_w != self->m_width || new_h != self->m_height) {
                self->m_width = new_w;
                self->m_height = new_h;
                if (self->m_callbacks.on_resize)
                    self->m_callbacks.on_resize(new_w, new_h);
            }
        }
        // w==0 && h==0 means compositor lets us choose — keep current size
    }
    static void toplevel_close(void* data, xdg_toplevel*) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (self->m_callbacks.on_close) self->m_callbacks.on_close();
        self->m_closed = true;
    }
    static constexpr xdg_toplevel_listener s_toplevel_listener = {
        toplevel_configure, toplevel_close
    };

    // ── Seat listener ─────────────────────────────────────────────────
    static void seat_capabilities(void* data, wl_seat* seat, uint32_t caps) {
        auto* self = static_cast<WaylandWindow*>(data);
        bool has_keyboard = caps & WL_SEAT_CAPABILITY_KEYBOARD;
        bool has_pointer  = caps & WL_SEAT_CAPABILITY_POINTER;

        if (has_keyboard && !self->m_keyboard) {
            self->m_keyboard = wl_seat_get_keyboard(seat);
            wl_keyboard_add_listener(self->m_keyboard, &s_keyboard_listener, self);
        } else if (!has_keyboard && self->m_keyboard) {
            wl_keyboard_destroy(self->m_keyboard);
            self->m_keyboard = nullptr;
        }

        if (has_pointer && !self->m_pointer) {
            self->m_pointer = wl_seat_get_pointer(seat);
            wl_pointer_add_listener(self->m_pointer, &s_pointer_listener, self);
        } else if (!has_pointer && self->m_pointer) {
            wl_pointer_destroy(self->m_pointer);
            self->m_pointer = nullptr;
        }
    }
    static void seat_name(void*, wl_seat*, const char*) {}
    static constexpr wl_seat_listener s_seat_listener = { seat_capabilities, seat_name };

    // ── Keyboard listener ─────────────────────────────────────────────
    static void kbd_keymap(void* data, wl_keyboard*, uint32_t format,
                           int32_t fd, uint32_t size) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) {
            close(fd);
            return;
        }
        char* map_str = static_cast<char*>(
            mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0));
        if (map_str == MAP_FAILED) {
            close(fd);
            return;
        }

        if (self->m_xkb_state) { xkb_state_unref(self->m_xkb_state); self->m_xkb_state = nullptr; }
        if (self->m_xkb_keymap) { xkb_keymap_unref(self->m_xkb_keymap); self->m_xkb_keymap = nullptr; }

        self->m_xkb_keymap = xkb_keymap_new_from_string(
            self->m_xkb_ctx, map_str, XKB_KEYMAP_FORMAT_TEXT_V1,
            XKB_KEYMAP_COMPILE_NO_FLAGS);
        munmap(map_str, size);
        close(fd);

        if (self->m_xkb_keymap) {
            self->m_xkb_state = xkb_state_new(self->m_xkb_keymap);
        }
    }
    static void kbd_enter(void* data, wl_keyboard*, uint32_t, wl_surface*, wl_array*) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (self->m_callbacks.on_focus) self->m_callbacks.on_focus(true);
    }
    static void kbd_leave(void* data, wl_keyboard*, uint32_t, wl_surface*) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (self->m_callbacks.on_focus) self->m_callbacks.on_focus(false);
    }
    static void kbd_key(void* data, wl_keyboard*, uint32_t, uint32_t,
                        uint32_t key, uint32_t state) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (!self->m_xkb_state) return;

        // Wayland key codes are evdev codes; XKB adds 8 to get the keycode
        xkb_keycode_t keycode = key + 8;
        bool pressed = (state == WL_KEYBOARD_KEY_STATE_PRESSED);

        xkb_keysym_t keysym = xkb_state_key_get_one_sym(self->m_xkb_state, keycode);

        KeyAction action;
        if (keysym_to_key_action(static_cast<uint32_t>(keysym), action)) {
            if (self->m_callbacks.on_key) self->m_callbacks.on_key(action, pressed);
        }

        // Text input (only on press)
        if (pressed && self->m_callbacks.on_text_input) {
            char buf[64] = {};
            int len = xkb_state_key_get_utf8(self->m_xkb_state, keycode, buf, sizeof(buf) - 1);
            if (len > 0 && static_cast<unsigned char>(buf[0]) >= 32) {
                self->m_callbacks.on_text_input(buf);
            }
        }
    }
    static void kbd_modifiers(void* data, wl_keyboard*, uint32_t,
                              uint32_t mods_depressed, uint32_t mods_latched,
                              uint32_t mods_locked, uint32_t group) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (self->m_xkb_state) {
            xkb_state_update_mask(self->m_xkb_state,
                mods_depressed, mods_latched, mods_locked, 0, 0, group);
        }
    }
    static void kbd_repeat_info(void*, wl_keyboard*, int32_t, int32_t) {}

    static constexpr wl_keyboard_listener s_keyboard_listener = {
        kbd_keymap, kbd_enter, kbd_leave, kbd_key, kbd_modifiers, kbd_repeat_info
    };

    // ── Pointer listener ──────────────────────────────────────────────
    static void ptr_enter(void*, wl_pointer*, uint32_t, wl_surface*,
                          wl_fixed_t, wl_fixed_t) {}
    static void ptr_leave(void*, wl_pointer*, uint32_t, wl_surface*) {}
    static void ptr_motion(void* data, wl_pointer*, uint32_t,
                           wl_fixed_t sx, wl_fixed_t sy) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (self->m_callbacks.on_mouse_move) {
            self->m_callbacks.on_mouse_move(
                wl_fixed_to_double(sx), wl_fixed_to_double(sy));
        }
    }
    static void ptr_button(void* data, wl_pointer*, uint32_t, uint32_t,
                           uint32_t button, uint32_t state) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (!self->m_callbacks.on_mouse_button) return;

        bool pressed = (state == WL_POINTER_BUTTON_STATE_PRESSED);
        // Linux evdev button codes: BTN_LEFT=272, BTN_RIGHT=273, BTN_MIDDLE=274
        int btn = -1;
        switch (button) {
            case 272: btn = 0; break; // Left
            case 273: btn = 1; break; // Right
            case 274: btn = 2; break; // Middle
        }
        if (btn >= 0)
            self->m_callbacks.on_mouse_button(btn, pressed);
    }
    static void ptr_axis(void* data, wl_pointer*, uint32_t, uint32_t axis,
                         wl_fixed_t value) {
        auto* self = static_cast<WaylandWindow*>(data);
        if (!self->m_callbacks.on_scroll) return;

        double v = wl_fixed_to_double(value);
        if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL)
            self->m_callbacks.on_scroll(0.0f, static_cast<float>(-v / 10.0));
        else
            self->m_callbacks.on_scroll(static_cast<float>(v / 10.0), 0.0f);
    }
    static void ptr_frame(void*, wl_pointer*) {}
    static void ptr_axis_source(void*, wl_pointer*, uint32_t) {}
    static void ptr_axis_stop(void*, wl_pointer*, uint32_t, uint32_t) {}
    static void ptr_axis_discrete(void*, wl_pointer*, uint32_t, int32_t) {}

    static constexpr wl_pointer_listener s_pointer_listener = {
        ptr_enter, ptr_leave, ptr_motion, ptr_button, ptr_axis,
        ptr_frame, ptr_axis_source, ptr_axis_stop, ptr_axis_discrete
    };

    // ── Members ───────────────────────────────────────────────────────
    wl_display*    m_display    = nullptr;
    wl_registry*   m_registry   = nullptr;
    wl_compositor* m_compositor = nullptr;
    wl_seat*       m_seat       = nullptr;
    wl_surface*    m_surface    = nullptr;
    wl_keyboard*   m_keyboard   = nullptr;
    wl_pointer*    m_pointer    = nullptr;

    xdg_wm_base*      m_xdg_wm_base  = nullptr;
    xdg_surface*       m_xdg_surface  = nullptr;
    xdg_toplevel*      m_toplevel     = nullptr;

    zxdg_decoration_manager_v1*     m_deco_manager = nullptr;
    zxdg_toplevel_decoration_v1*    m_decoration   = nullptr;

    xkb_context* m_xkb_ctx    = nullptr;
    xkb_keymap*  m_xkb_keymap = nullptr;
    xkb_state*   m_xkb_state  = nullptr;

    WindowCallbacks m_callbacks;
    uint32_t m_width  = 0;
    uint32_t m_height = 0;
    bool m_closed     = false;
    bool m_configured = false;
};

bool wayland_probe() {
    wl_display* d = wl_display_connect(nullptr);
    if (!d) return false;
    wl_display_disconnect(d);
    return true;
}

std::unique_ptr<PlatformWindow> create_wayland_window() {
    return std::make_unique<WaylandWindow>();
}

} // namespace engine::core

#endif // __linux__ && ENGINE_HAS_WAYLAND
